"""ARCH-002/003 core domain tables

Revision ID: 58b8efe84ede
Revises: 
Create Date: 2026-07-08 21:57:46.601596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '58b8efe84ede'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_sync_state',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('page_token', sa.Text(), nullable=True),
    sa.Column('watch_channel_id', sa.Text(), nullable=True),
    sa.Column('watch_resource_id', sa.Text(), nullable=True),
    sa.Column('watch_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_drive_sync_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'company' AND parent_id IS NULL) OR (type IN ('department', 'team') AND parent_id IS NOT NULL)", name='ck_organization_nodes_hierarchy_parent'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_organization_nodes_status'),
    sa.CheckConstraint("type IN ('company', 'department', 'team')", name='ck_organization_nodes_type'),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('position', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('department_node_id', sa.Integer(), nullable=True),
    sa.Column('team_node_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('employment_type', sa.Text(), nullable=True),
    sa.Column('resigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_node_id'], ['organization_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_node_id'], ['organization_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_user_id')
    )
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('document_tree_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_node_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'document_type' AND document_type_id IS NOT NULL) OR (type = 'work' AND document_type_id IS NULL)", name='ck_document_tree_nodes_type_ref'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_document_tree_nodes_status'),
    sa.CheckConstraint("type IN ('work', 'document_type')", name='ck_document_tree_nodes_type'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_node_id'], ['organization_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_tree_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_provider', sa.Text(), nullable=False),
    sa.Column('drive_file_id', sa.Text(), nullable=False),
    sa.Column('drive_name', sa.Text(), nullable=False),
    sa.Column('drive_web_url', sa.Text(), nullable=True),
    sa.Column('drive_mime_type', sa.Text(), nullable=False),
    sa.Column('drive_state', sa.Text(), nullable=False),
    sa.Column('drive_modified_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drive_fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('created_department_node_id', sa.Integer(), nullable=True),
    sa.Column('owning_department_node_id', sa.Integer(), nullable=True),
    sa.Column('organization_path', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('tree_path', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('related_products', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('read_roles', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('read_departments', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('read_positions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('access_logic', sa.Text(), nullable=False),
    sa.Column('sensitivity', sa.Text(), nullable=False),
    sa.Column('policy_preset', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("access_logic IN ('ANY', 'ALL', 'PRESET')", name='ck_documents_access_logic'),
    sa.CheckConstraint("drive_state IN ('active', 'trashed', 'removed', 'out_of_scope')", name='ck_documents_drive_state'),
    sa.CheckConstraint("sensitivity IN ('normal', 'sensitive')", name='ck_documents_sensitivity'),
    sa.CheckConstraint("source_provider IN ('google_drive')", name='ck_documents_source_provider'),
    sa.ForeignKeyConstraint(['created_department_node_id'], ['organization_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owning_department_node_id'], ['organization_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_provider', 'drive_file_id', name='uq_documents_provider_file')
    )
    op.create_index('ix_documents_drive_state', 'documents', ['drive_state'], unique=False)
    op.create_index('ix_documents_organization_path_gin', 'documents', ['organization_path'], unique=False, postgresql_using='gin')
    op.create_index('ix_documents_owning_department', 'documents', ['owning_department_node_id'], unique=False)
    op.create_index('ix_documents_read_departments_gin', 'documents', ['read_departments'], unique=False, postgresql_using='gin')
    op.create_index('ix_documents_tree_path_gin', 'documents', ['tree_path'], unique=False, postgresql_using='gin')
    op.create_table('document_path_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('previous_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_related_departments',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('organization_node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_node_id'], ['organization_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('document_id', 'organization_node_id')
    )
    op.create_table('document_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('target_document_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('source_label', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relation_type IN ('related', 'references', 'supersedes', 'duplicate_candidate')", name='ck_document_relations_type'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', 'target_document_id', 'relation_type', name='uq_document_relations_source_target_type')
    )
    op.create_table('drive_sync_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('drive_file_id', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('webhook_received', 'changes_listed', 'document_upserted', 'document_unavailable', 'candidate_staled', 'reanalysis_enqueued', 'sync_failed')", name='ck_drive_sync_events_event_type'),
    sa.CheckConstraint("result IN ('success', 'skipped', 'failed')", name='ck_drive_sync_events_result'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drive_sync_events_document', 'drive_sync_events', ['document_id'], unique=False)
    op.create_index('ix_drive_sync_events_occurred_at', 'drive_sync_events', ['occurred_at'], unique=False)
    op.create_table('metadata_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('read_capability', sa.Text(), nullable=False),
    sa.Column('candidate_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("read_capability IN ('content_read', 'metadata_only')", name='ck_metadata_candidates_read_capability'),
    sa.CheckConstraint("state IN ('pending', 'stale', 'approved', 'rejected', 'blocked')", name='ck_metadata_candidates_state'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metadata_candidates_document_created', 'metadata_candidates', ['document_id', 'created_at'], unique=False)
    op.create_index('ix_metadata_candidates_state', 'metadata_candidates', ['state'], unique=False)
    op.create_index('uq_metadata_candidates_one_pending', 'metadata_candidates', ['document_id'], unique=True, postgresql_where=sa.text("state = 'pending'"))
    op.create_table('relation_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('raw_label', sa.Text(), nullable=False),
    sa.Column('suggested_relation_type', sa.Text(), nullable=False),
    sa.Column('target_document_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'unresolved', 'approved', 'removed')", name='ck_relation_candidates_state'),
    sa.CheckConstraint("suggested_relation_type IN ('related', 'references', 'supersedes', 'duplicate_candidate')", name='ck_relation_candidates_suggested_type'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_queue_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('drive_file_id', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('external_task_id', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('payload_ref', sa.Text(), nullable=True),
    sa.Column('result_ref', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('classification', 'stale_reanalysis')", name='ck_ai_queue_jobs_job_type'),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'candidate_saved', 'validation_failed', 'failed', 'timeout', 'stale')", name='ck_ai_queue_jobs_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['metadata_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_type', 'document_id', 'fingerprint', 'idempotency_key', name='uq_ai_queue_jobs_idempotency')
    )
    op.create_index('ix_ai_queue_jobs_document_created', 'ai_queue_jobs', ['document_id', 'created_at'], unique=False)
    op.create_index('ix_ai_queue_jobs_document_fingerprint', 'ai_queue_jobs', ['document_id', 'fingerprint'], unique=False)
    op.create_index('ix_ai_queue_jobs_external_task', 'ai_queue_jobs', ['external_task_id'], unique=False)
    op.create_index('ix_ai_queue_jobs_status_next_run', 'ai_queue_jobs', ['status', 'next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_queue_jobs_status_next_run', table_name='ai_queue_jobs')
    op.drop_index('ix_ai_queue_jobs_external_task', table_name='ai_queue_jobs')
    op.drop_index('ix_ai_queue_jobs_document_fingerprint', table_name='ai_queue_jobs')
    op.drop_index('ix_ai_queue_jobs_document_created', table_name='ai_queue_jobs')
    op.drop_table('ai_queue_jobs')
    op.drop_table('relation_candidates')
    op.drop_index('uq_metadata_candidates_one_pending', table_name='metadata_candidates', postgresql_where=sa.text("state = 'pending'"))
    op.drop_index('ix_metadata_candidates_state', table_name='metadata_candidates')
    op.drop_index('ix_metadata_candidates_document_created', table_name='metadata_candidates')
    op.drop_table('metadata_candidates')
    op.drop_index('ix_drive_sync_events_occurred_at', table_name='drive_sync_events')
    op.drop_index('ix_drive_sync_events_document', table_name='drive_sync_events')
    op.drop_table('drive_sync_events')
    op.drop_table('document_relations')
    op.drop_table('document_related_departments')
    op.drop_table('document_path_histories')
    op.drop_index('ix_documents_tree_path_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_read_departments_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_owning_department', table_name='documents')
    op.drop_index('ix_documents_organization_path_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_drive_state', table_name='documents')
    op.drop_table('documents')
    op.drop_table('document_tree_nodes')
    op.drop_table('document_types')
    op.drop_table('users')
    op.drop_table('organization_nodes')
    op.drop_table('drive_sync_state')
    # ### end Alembic commands ###
